cabal-version:      3.8
build-type:         Simple
name:               yamlet
version:            1.0.0.0
license:            BSD-3-Clause
license-file:       LICENSE
category:           Text, Data
maintainer:         andrzej@rybczak.net
author:             Andrzej Rybczak
synopsis:           A pure, fast and conforming YAML 1.2 library.

description:
  A YAML 1.2.2 parser and emitter written in Haskell, with error messages that
  point to the line and the column of the problem. It has few dependencies.

extra-doc-files:
  CHANGELOG.md
  README.md

extra-source-files:
  tests/fixtures/error-messages.txt
  tests/fixtures/yaml-test-suite/**/*.event
  tests/fixtures/yaml-test-suite/**/*.json
  tests/fixtures/yaml-test-suite/**/*.token
  tests/fixtures/yaml-test-suite/**/*.yaml
  tests/fixtures/yaml-test-suite/**/===
  tests/fixtures/yaml-test-suite/**/error

tested-with: GHC ^>= { 9.2, 9.4, 9.6, 9.8, 9.10, 9.12, 9.14 }

common language
    ghc-options:        -Wall
                        -Werror=missing-deriving-strategies
                        -Werror=prepositive-qualified-module

    default-language:   GHC2021

    default-extensions: DerivingStrategies
                        DuplicateRecordFields
                        LambdaCase
                        MultiWayIf
                        NoFieldSelectors
                        OverloadedRecordDot
                        OverloadedStrings

library
    import:         language

    ghc-options:    -O2

    build-depends:    base       >= 4.16 && < 5
                    , bytestring >= 0.11
                    , containers >= 0.6.3.1
                    , deepseq    >= 1.4
                    , scientific >= 0.3.7
                    , text       >= 2.0.2
                    , text-builder-linear >= 0.1.3
                    , time       >= 1.11
                    , uuid-types >= 1.0.6

    hs-source-dirs:  src

    exposed-modules: Yamlet
                     Yamlet.Decode
                     Yamlet.Encode
                     Yamlet.Error
                     Yamlet.Internal.Comments
                     Yamlet.Internal.Compose
                     Yamlet.Internal.Emit
                     Yamlet.Internal.Input
                     Yamlet.Internal.Parser
                     Yamlet.Internal.Parser.Chars
                     Yamlet.Internal.Parser.Hints
                     Yamlet.Internal.Parser.Monad
                     Yamlet.Internal.Render
                     Yamlet.Internal.Schema
                     Yamlet.Internal.Syntax
                     Yamlet.Internal.Time
                     Yamlet.Node
                     Yamlet.Schema
                     Yamlet.Syntax

test-suite test
    import:         language

    ghc-options:    -threaded -rtsopts

    build-depends:    base
                    , aeson
                    , attoparsec
                    , attoparsec-aeson
                    , bytestring
                    , containers
                    , directory
                    , filepath
                    , yamlet
                    , scientific
                    , tasty
                    , tasty-hunit
                    , tasty-quickcheck
                    , QuickCheck
                    , text
                    , time
                    , uuid-types
                    , vector

    hs-source-dirs: tests

    type:           exitcode-stdio-1.0
    main-is:        Main.hs

    other-modules:  DecodeTests
                    EncodeTests
                    Events
                    RenderTests
                    TestSuite

benchmark bench
    import:         language

    ghc-options:    -rtsopts

    build-depends:    base
                    , aeson
                    , bytestring
                    , containers
                    , deepseq
                    , yamlet
                    , HsYAML
                    , scientific
                    , tasty-bench
                    , text
                    , yaml

    hs-source-dirs: bench

    type:           exitcode-stdio-1.0
    main-is:        Main.hs
