module RenderTests (renderTests) where

import Data.Text qualified as T
import Test.QuickCheck
import Test.Tasty
import Test.Tasty.HUnit
import Test.Tasty.QuickCheck

import Yamlet.Syntax

renderTests :: TestTree
renderTests = testGroup "Render"
  [ testCase "workflow" test_workflow
  , testCase "styles" test_styles
  , testCase "fallbacks" test_fallbacks
  , testCase "force block" test_forceBlock
  , testCase "documents" test_documents
  , testProperty "round trip" prop_roundTrip
  ]

-- | A generated file with a header, and empty lines between the jobs and
-- between the steps.
test_workflow :: Assertion
test_workflow = assertEqual "output" expected (renderSyntax opts [doc])
  where
    opts :: RenderOptions
    opts = defaultRenderOptions { extraLines = extra }

    extra :: [Segment] -> [ExtraLine]
    extra = \case
      [] -> [Comment "Generated by haskell-gha.\nDo not edit."]
      [Key "jobs"] -> [EmptyLine]
      [Key "jobs", Key _] -> [EmptyLine]
      [Key "jobs", Key _, Key "steps", Index i] | i > 0 -> [EmptyLine]
      _ -> []

    doc :: Document
    doc = Document Nothing False False $ mappingNode
      [ (plainNode "name", plainNode "CI")
      , (plainNode "jobs", mappingNode
          [ (plainNode "build", mappingNode
              [ (plainNode "runs-on", plainNode "ubuntu-latest")
              , (plainNode "steps", sequenceNode
                  [ mappingNode [(plainNode "uses", plainNode "actions/checkout@v4")]
                  , mappingNode
                      [ (plainNode "name", plainNode "Build")
                      , (plainNode "run", scalarNode Literal "cabal build\ncabal test\n")
                      ]
                  ])
              ])
          , (plainNode "lint", mappingNode [(plainNode "ghc", scalarNode SingleQuoted "9.10")])
          ])
      ]

    expected :: T.Text
    expected = T.unlines
      [ "# Generated by haskell-gha."
      , "# Do not edit."
      , "name: CI"
      , ""
      , "jobs:"
      , ""
      , "  build:"
      , "    runs-on: ubuntu-latest"
      , "    steps:"
      , "    - uses: actions/checkout@v4"
      , ""
      , "    - name: Build"
      , "      run: |"
      , "        cabal build"
      , "        cabal test"
      , ""
      , "  lint:"
      , "    ghc: '9.10'"
      ]

-- | Parsing and rendering gives back the input.
test_styles :: Assertion
test_styles = assertEqual "output" (Right input) (renderSyntax defaultRenderOptions <$> parseDocumentsText input)
  where
    input :: T.Text
    input = T.unlines
      [ "plain: text"
      , "single: 'it''s'"
      , "double: \"a\\tb\""
      , "literal: |"
      , "  line 1"
      , "   line 2"
      , "folded: >-"
      , "  first"
      , ""
      , "  second"
      , "list:"
      , "- a"
      , "- - b"
      , "  - c: d"
      , "flow: [a, 'b', {c: d}]"
      , "anchor: &x value"
      , "alias: *x"
      , "*x : key alias"
      , "tagged: !!str 12"
      , "local: !point {x: 1}"
      , "empty:"
      , "[complex, key]: value"
      ]

test_fallbacks :: Assertion
test_fallbacks = do
  let render :: Node -> T.Text
      render n = renderSyntax defaultRenderOptions [Document Nothing False False n]
  assertEqual "plain with a colon" "'a: b'\n" (render (plainNode "a: b"))
  assertEqual "plain number stays plain" "12\n" (render (plainNode "12"))
  assertEqual "single-quoted line break" "\"a\\nb\"\n" (render (scalarNode SingleQuoted "a\nb"))
  assertEqual "keep indicator" "- \"a\\n\\n\"\n- b\n"
    (render (sequenceNode [scalarNode Literal "a\n\n", plainNode "b"]))
  assertEqual "block scalar in a flow collection" "[\"a\\n\"]\n"
    (render (Sequence noOffset noProps Flow [scalarNode Literal "a\n"]))
  assertEqual "empty item of a flow sequence" "[!!null, a]\n"
    (render (Sequence noOffset noProps Flow [plainNode "", plainNode "a"]))
  assertEqual "empty key" "?\n: a\n" (render (mappingNode [(plainNode "", plainNode "a")]))

test_forceBlock :: Assertion
test_forceBlock = assertEqual "output" (Right expected)
  (renderSyntax defaultRenderOptions { forceBlock = True } <$> parseDocumentsText input)
  where
    input :: T.Text
    input = "list: [a, [b, c], {d: e}]\nkey: [[f]]\n"

    expected :: T.Text
    expected = T.unlines
      [ "list:"
      , "- a"
      , "- - b"
      , "  - c"
      , "- d: e"
      , "key:"
      , "- - f"
      ]

test_documents :: Assertion
test_documents = assertEqual "output" (Right input) (renderSyntax defaultRenderOptions <$> parseDocumentsText input)
  where
    input :: T.Text
    input = T.unlines
      [ "first"
      , "--- second"
      , "..."
      , "%YAML 1.2"
      , "---"
      , "a: b"
      , "---"
      ]

-- | Rendering a tree and parsing the result gives the same tree, except for
-- the styles and the offsets.
prop_roundTrip :: Tree -> Property
prop_roundTrip (Tree n) = check defaultRenderOptions .&&. check withExtras
  where
    check :: RenderOptions -> Property
    check opts =
      let out = renderSyntax opts [Document Nothing False False n]
      in counterexample (T.unpack out) $ case parseDocumentsText out of
           Right [doc] -> strip doc.root === strip (flowItems False n)
           r -> counterexample (show r) False

    -- Extra lines everywhere, e.g. after a block scalar.
    withExtras :: RenderOptions
    withExtras = defaultRenderOptions
      { extraLines = const [EmptyLine, Comment "a comment", EmptyLine]
      }

    strip :: Node -> Node
    strip = \case
      Scalar _ p _ t -> Scalar noOffset p Plain t
      Sequence _ p _ xs -> Sequence noOffset p Block (map strip xs)
      Mapping _ p _ kvs -> Mapping noOffset p Block [ (strip k, strip v) | (k, v) <- kvs ]
      Alias _ a -> Alias noOffset a

    -- The renderer gives an empty item of a flow sequence a tag.
    flowItems :: Bool -> Node -> Node
    flowItems inFlow = \case
      Sequence o p s xs ->
        let inFlow' = inFlow || s == Flow
        in Sequence o p s (map (item inFlow' . flowItems inFlow') xs)
      Mapping o p s kvs ->
        let inFlow' = inFlow || s == Flow
        in Mapping o p s [ (flowItems inFlow' k, flowItems inFlow' v) | (k, v) <- kvs ]
      x -> x

    item :: Bool -> Node -> Node
    item inFlow = \case
      Scalar o (Props Nothing NoTag) Plain "" | inFlow ->
        Scalar o (Props Nothing (Tag "tag:yaml.org,2002:null")) Plain ""
      x -> x

newtype Tree = Tree Node
  deriving stock Show

instance Arbitrary Tree where
  arbitrary = Tree <$> sized genNode

genNode :: Int -> Gen Node
genNode size
  | size <= 1 = genScalar
  | otherwise = frequency
    [ (3, genScalar)
    , (1, Alias noOffset <$> genAnchor)
    , (1, Sequence noOffset <$> genProps <*> genStyle <*> genList)
    , (1, Mapping noOffset <$> genProps <*> genStyle <*> genEntries)
    ]
  where
    genList :: Gen [Node]
    genList = do
      k <- choose (0, 4)
      vectorOf k (genNode (size `div` 3))

    genEntries :: Gen [(Node, Node)]
    genEntries = do
      k <- choose (0, 4)
      vectorOf k ((,) <$> genNode (size `div` 4) <*> genNode (size `div` 3))

    genStyle :: Gen CollectionStyle
    genStyle = elements [Block, Flow]

genScalar :: Gen Node
genScalar = Scalar noOffset <$> genProps <*> elements [minBound .. maxBound] <*> genText

genProps :: Gen Props
genProps = Props <$> oneof [pure Nothing, Just <$> genAnchor] <*> elements
  [ NoTag, NoTag, NonSpecificTag, Tag "tag:yaml.org,2002:str", Tag "!local"
  , Tag "tag:example.com,2000:x"
  ]

genAnchor :: Gen T.Text
genAnchor = elements ["a", "b", "anchor"]

genText :: Gen T.Text
genText = oneof
  [ elements tricky
  , T.pack <$> listOf genChar
  , T.intercalate "\n" <$> listOf (T.pack <$> listOf genChar)
  ]
  where
    tricky :: [T.Text]
    tricky =
      [ "", " ", "-", "- a", "? a", ": a", "a: b", "a:b", "#", "a #b", "true", "12"
      , "---", "...", "foo\n", "\nfoo", "  lead", "trail  ", "a\n\nb\n\n", "\n"
      , "\n\n", " \n", "a\n ", "|", ">", "[a]", "{a: b}", "a, b", "key:", "\r\n"
      , "a\n  b\nc", "  a\nb", "a\n\n  b\n\nc\n"
      ]

    genChar :: Gen Char
    genChar = frequency
      [ (10, elements "abc xyz-:#,[]{}'\"!&*?|>%@`\\")
      , (2, elements "\t\r\x85\xA0\x2028\xFEFF\x01")
      , (1, arbitrary)
      ]
