module RenderTests (renderTests) where

import Control.Monad
import Data.List qualified as L
import Data.Maybe
import Data.Text qualified as T
import Test.Tasty
import Test.Tasty.HUnit
import Test.Tasty.QuickCheck

import Helpers
import Thunks
import Yamlet hiding (Commented (..))
import Yamlet.Syntax

renderTests :: TestTree
renderTests =
  testGroup
    "Render"
    [ testCase "workflow" test_workflow
    , testCase "styles" test_styles
    , testCase "fallbacks" test_fallbacks
    , testCase "force block" test_forceBlock
    , testCase "documents" test_documents
    , testCase "lines of scalars" test_scalarLines
    , slow $ testCase "many invalid anchor names" test_manyAnchors
    , slow $ testCase "deep comment" test_deepComment
    , slow $ testCase "many escaped line breaks" test_escapedBreaks
    , testGroup
        "comments"
        [ testCase "attachment" test_attachment
        , testCase "configuration" test_configuration
        , testCase "round trip" test_commentRoundTrip
        , testCase "several hashes" test_hashes
        , testCase "moved comments" test_movedComments
        , testCase "lines after a list" test_linesAfterList
        , testCase "lines below an indicator" test_linesBelowIndicator
        , testCase "no thunks" test_noThunks
        , testProperty "no thunks in generated documents" prop_noThunks
        ]
    , testProperty "round trip" prop_roundTrip
    ]

-- | A generated file with a header, and empty lines between the jobs and
-- between the steps. The header is on the root, so the file has no start
-- marker.
test_workflow :: Assertion
test_workflow = do
  let out = renderSyntax defaultRenderOptions [doc]
  assertEqual "output" expected out
  assertEqual
    "header read back"
    (Right [[Comment "Generated by haskell-gha.", Comment "Do not edit.", EmptyLine]])
    (map (\d -> d.root.comments.before) <$> parseDocumentsText out)
  where
    doc :: Document
    doc =
      Document
        { version = Nothing
        , explicitStart = False
        , explicitEnd = False
        , docComments = noComments
        , root =
            withHeader $
              mappingNode
                [ (plainNode "name", plainNode "CI")
                ,
                  ( withEmptyLine (plainNode "jobs")
                  , mappingNode
                      [
                        ( withEmptyLine (plainNode "build")
                        , mappingNode
                            [ (plainNode "runs-on", plainNode "ubuntu-latest")
                            ,
                              ( plainNode "steps"
                              , sequenceNode
                                  [ mappingNode [(plainNode "uses", plainNode "actions/checkout@v4")]
                                  , withEmptyLine $
                                      mappingNode
                                        [ (plainNode "name", plainNode "Build")
                                        , (plainNode "run", scalarNode Literal "cabal build\ncabal test\n")
                                        ]
                                  ]
                              )
                            ]
                        )
                      , (withEmptyLine (plainNode "lint"), mappingNode [(plainNode "ghc", scalarNode SingleQuoted "9.10")])
                      ]
                  )
                ]
        }

    withEmptyLine :: Node -> Node
    withEmptyLine n = n {comments = n.comments {before = [EmptyLine]}}

    withHeader :: Node -> Node
    withHeader n = n {comments = n.comments {before = [Comment "Generated by haskell-gha.\nDo not edit."]}}

    expected :: T.Text
    expected =
      T.unlines
        [ "# Generated by haskell-gha."
        , "# Do not edit."
        , ""
        , "name: CI"
        , ""
        , "jobs:"
        , ""
        , "  build:"
        , "    runs-on: ubuntu-latest"
        , "    steps:"
        , "    - uses: actions/checkout@v4"
        , ""
        , "    - name: Build"
        , "      run: |"
        , "        cabal build"
        , "        cabal test"
        , ""
        , "  lint:"
        , "    ghc: '9.10'"
        ]

test_styles :: Assertion
test_styles = rendersBack "output" input
  where
    input :: T.Text
    input =
      T.unlines
        [ "plain: text"
        , "single: 'it''s'"
        , "double: \"a\\tb\""
        , "literal: |"
        , "  line 1"
        , "   line 2"
        , "folded: >-"
        , "  first"
        , ""
        , "  second"
        , "list:"
        , "- a"
        , "- - b"
        , "  - c: d"
        , "flow: [a, 'b', {c: d}]"
        , "anchor: &x value"
        , "alias: *x"
        , "*x : key alias"
        , "tagged: !!str 12"
        , "local: !point {x: 1}"
        , "empty:"
        , "[complex, key]: value"
        ]

-- | The text of a document with the node as its root.
render :: Node -> T.Text
render n = renderSyntax defaultRenderOptions [document n]

-- | Parsing and rendering gives back the input.
rendersBack :: String -> T.Text -> Assertion
rendersBack preface input = assertEqual preface (Right input) (renderSyntax defaultRenderOptions <$> parseDocumentsText input)

-- | Parsing and rendering gives the expected text, which gives itself back.
rendersAs :: String -> T.Text -> T.Text -> Assertion
rendersAs preface expected input = do
  assertEqual preface (Right expected) (renderSyntax defaultRenderOptions <$> parseDocumentsText input)
  rendersBack (preface ++ ", rendered again") expected

test_fallbacks :: Assertion
test_fallbacks = do
  assertEqual "plain with a colon" "'a: b'\n" (render (plainNode "a: b"))
  assertEqual "plain number stays plain" "12\n" (render (plainNode "12"))
  assertEqual "single-quoted line break" "\"a\\nb\"\n" (render (scalarNode SingleQuoted "a\nb"))
  assertEqual "literal with an indicator at the top level" "\" a\\nb\"\n" (render (scalarNode Literal " a\nb"))
  assertEqual "folded with an indicator at the top level" "\" a\\nb\"\n" (render (scalarNode Folded " a\nb"))
  let withLineBelow :: Node -> Node
      withLineBelow n = n {comments = noComments {after = [Comment "c"]}}
  assertEqual "empty literal with a line below at the top level" "\"\"\n# c\n" (render (withLineBelow (scalarNode Literal "")))
  assertEqual "empty folded with a line below at the top level" "\"\"\n# c\n" (render (withLineBelow (scalarNode Folded "")))
  assertEqual
    "literal of only line breaks with a line below at the top level"
    (Right [(ScalarContent DoubleQuoted "\n", [("", "after", "c")])])
    ( map (\d -> (d.root.content, commentsOf d))
        <$> parseDocumentsText (render (withLineBelow (scalarNode Literal "\n")))
    )
  assertEqual "literal with a line below in a list" "- |-\n# c\n" (render (sequenceNode [withLineBelow (scalarNode Literal "")]))
  assertEqual "literal with an indicator in a list" "- |2-\n   a\n  b\n" (render (sequenceNode [scalarNode Literal " a\nb"]))
  assertEqual "folded with a tab in a list" "- >2-\n  \ta\n  b\n" (render (sequenceNode [scalarNode Folded "\ta\nb"]))
  -- A block scalar cannot hold the character, so the lines below it stay
  -- deeper than the key, as below any quoted scalar.
  let quotedBlocks =
        mappingNode
          [ (plainNode "a", withLineBelow (scalarNode Literal "x\DEL"))
          , (plainNode "b", sequenceNode [withLineBelow (scalarNode Folded "x\DEL"), plainNode "y"])
          , (sequenceNode [plainNode "k"], withLineBelow (scalarNode Literal "x\DEL"))
          ]
  assertEqual
    "lines below a block scalar in double quotes"
    "a: \"x\\x7F\"\n  # c\nb:\n- \"x\\x7F\"\n  # c\n- y\n? - k\n: \"x\\x7F\"\n  # c\n"
    (render quotedBlocks)
  assertEqual
    "lines below a block scalar in double quotes read back"
    (Right [[("/a", "after", "c"), ("/b/0", "after", "c"), ("/?", "after", "c")]])
    (map commentsOf <$> parseDocumentsText (render quotedBlocks))
  assertEqual
    "keep indicator"
    "- |+\n  a\n\n- b\n"
    (render (sequenceNode [scalarNode Literal "a\n\n", (plainNode "b") {comments = noComments {before = [EmptyLine]}}]))
  assertEqual
    "block scalar in a flow collection"
    "[\"a\\n\"]\n"
    (render (contentNode (SequenceContent Flow [scalarNode Literal "a\n"])))
  -- YAML 1.1 parsers read a comma or a bracket right after a tag as part of
  -- the tag.
  assertEqual
    "empty item of a flow sequence"
    "[!!null , a, !!null ]\n"
    (render (contentNode (SequenceContent Flow [plainNode "", plainNode "a", plainNode ""])))
  assertEqual
    "empty tagged values in flow collections"
    (Right "[80, !!str , 443]\n---\n{a: !!str , b: !!str }\n")
    (renderSyntax defaultRenderOptions <$> parseDocumentsText "[80, !!str , 443]\n---\n{a: !!str , b: !!str }\n")
  -- YAML 1.1 parsers misread or reject these plain scalars, empty keys and
  -- empty values in flow collections.
  assertEqual
    "indicators in plain scalars of a flow collection"
    "['?a', 'a?b', ':a', 'a:?', a:b, -a]\n"
    (render (contentNode (SequenceContent Flow (map plainNode ["?a", "a?b", ":a", "a:?", "a:b", "-a"]))))
  rendersAs
    "empty keys and values in flow mappings"
    "{k: , a: 1}\n---\n{? : x}\n---\n{? }\n"
    "{k:, a: 1}\n---\n{: x}\n---\n{: }\n"
  -- libyaml and PyYAML reject an implicit key of more than 1024 characters
  -- in a flow mapping too.
  let flowEntry :: Node -> Node -> Node
      flowEntry k v = contentNode (MappingContent Flow [(k, v)])
      longest = T.replicate 1024 "a"
      long = T.replicate 1025 "a"
      anchoredKey = (plainNode (T.replicate 1020 "a")) {props = noProps {anchor = Just "anchor"}}
  assertEqual "flow key of the longest length" ("{" <> longest <> ": 1}\n") (render (flowEntry (plainNode longest) (plainNode "1")))
  assertEqual "long flow key" ("{? " <> long <> " : 1}\n") (render (flowEntry (plainNode long) (plainNode "1")))
  assertEqual "long flow key without a value" ("{? " <> long <> "}\n") (render (flowEntry (plainNode long) (plainNode "")))
  assertEqual
    "flow key that an anchor makes long"
    ("{? &anchor " <> T.replicate 1020 "a" <> " : 1}\n")
    (render (flowEntry anchoredKey (plainNode "1")))
  let longTag = "!" <> T.replicate 1100 "t"
      longTagged = (plainNode "") {props = noProps {tag = Tag longTag}}
  assertEqual
    "flow key that a tag makes long, without a value"
    ("{? " <> longTag <> " , b: c}\n")
    (render (contentNode (MappingContent Flow [(longTagged, plainNode ""), (plainNode "b", plainNode "c")])))
  assertEqual
    "long flow keys read back"
    (Right [Mapping [(String long, Int 1)], Mapping [(String long, Null)], Mapping [(String (T.replicate 1020 "a"), Int 1)]])
    ( decodeAllText @Value . renderSyntax defaultRenderOptions $
        map
          document
          [flowEntry (plainNode long) (plainNode "1"), flowEntry (plainNode long) (plainNode ""), flowEntry anchoredKey (plainNode "1")]
    )
  assertEqual "empty key" "?\n: a\n" (render (mappingNode [(plainNode "", plainNode "a")]))
  let emptyWithComment = (contentNode (SequenceContent Block [])) {comments = noComments {after = [Comment "c"]}}
      commented = mappingNode [(plainNode "k", emptyWithComment)]
  assertEqual "comment in an empty collection" "k: [\n  # c\n  ]\n" (render commented)
  assertEqual
    "comment in an empty collection reads back"
    (Right [[("/k", "after", "c")]])
    (map commentsOf <$> parseDocumentsText (render commented))
  let keyWithLineBelow :: Node -> Node
      keyWithLineBelow v = mappingNode [((plainNode "k") {comments = noComments {after = [Comment "c"]}}, v), (plainNode "l", plainNode "y")]
      flowSequence :: Node
      flowSequence = contentNode (SequenceContent Flow [plainNode "a"])
  assertEqual "lines after a key with a flow value" "# c\nk: [a]\nl: y\n" (render (keyWithLineBelow flowSequence))
  assertEqual
    "lines after a key with a flow value read back"
    (Right [[("/k:key", "before", "c")]])
    (map commentsOf <$> parseDocumentsText (render (keyWithLineBelow flowSequence)))
  assertEqual
    "lines after a key with an empty flow value"
    "# c\nk: {}\nl: y\n"
    (render (keyWithLineBelow (contentNode (MappingContent Flow []))))
  assertEqual
    "comment in an empty key"
    "? [\n  # c\n  ]\n: v\n"
    (render (mappingNode [(emptyWithComment, plainNode "v")]))
  assertEqual
    "comment in an empty key reads back"
    (Right [[("/?:key", "after", "c")]])
    (map commentsOf <$> parseDocumentsText (render (mappingNode [(emptyWithComment, plainNode "v")])))
  assertEqual
    "white space at the end of a comment"
    "# y\na # x\n"
    (render (plainNode "a") {comments = noComments {before = [Comment "y\t"], inline = Just "x "}})
  let anchored :: T.Text -> Node -> Node
      anchored a n = n {props = noProps {anchor = Just a}}
  assertEqual
    "invalid anchor names"
    "[&a_b x, *a_b, &a_b_2 y, *a_b_2, &anchor z, *anchor]\n"
    ( render . contentNode $
        SequenceContent
          Flow
          [ anchored "a b" (plainNode "x")
          , contentNode (AliasContent "a b")
          , anchored "a]b" (plainNode "y")
          , contentNode (AliasContent "a]b")
          , anchored "" (plainNode "z")
          , contentNode (AliasContent "")
          ]
    )
  let tagged :: T.Text -> Node
      tagged t = (plainNode "x") {props = noProps {tag = Tag t}}
      tagOf :: T.Text -> Either String [Tag]
      tagOf t = case parseDocumentsText (render (tagged t)) of
        Right docs -> Right [d.root.props.tag | d <- docs]
        Left err -> Left (show err)
  assertEqual "empty tag" "! x\n" (render (tagged ""))
  assertEqual "global tag" "!<tag:example.com,2000:x> x\n" (render (tagged "tag:example.com,2000:x"))
  assertEqual "tag with a directive" "%TAG !t74! %74\n---\n!t74!ag:x%3Ey x\n" (render (tagged "tag:x>y"))
  mapM_
    (\t -> assertEqual ("tag " ++ show t) (Right [Tag t]) (tagOf t))
    ["tag:x>y", "x%2", "foo", "#a b", "!a b", "tag:x%41", "tag:yaml.org,2002:a%", "\x100\&z"]
  assertEqual
    "directives after a document"
    (Right [(NoTag, ScalarContent Plain "a"), (Tag "foo", ScalarContent Plain "x")])
    ( map (\d -> (d.root.props.tag, d.root.content))
        <$> parseDocumentsText (renderSyntax defaultRenderOptions [document (plainNode "a"), document (tagged "foo")])
    )
  assertEqual
    "taken anchor name"
    "- &a_b x\n- &a_b_2 y\n- *a_b_2\n"
    (render (sequenceNode [anchored "a_b" (plainNode "x"), anchored "a b" (plainNode "y"), contentNode (AliasContent "a b")]))
  assertEqual
    "anchor names with line separators"
    "- &a_b x\n- &c_d y\n- *a_b\n- *c_d\n"
    ( render
        ( sequenceNode
            [ anchored "a\x2028\&b" (plainNode "x")
            , anchored "c\x2029\&d" (plainNode "y")
            , contentNode (AliasContent "a\x2028\&b")
            , contentNode (AliasContent "c\x2029\&d")
            ]
        )
    )

-- | The new names of many invalid anchor names with one base take linear
-- time, not quadratic.
test_manyAnchors :: Assertion
test_manyAnchors = do
  let names = map T.pack (mapM (const " ,[]{}") [1 .. 6 :: Int])
      tree = sequenceNode [(plainNode "x") {props = noProps {anchor = Just a}} | a <- names]
  assertEqual
    "first and last names"
    ["- &______ x", "- &_______" <> T.pack (show (length names)) <> " x"]
    ( case T.lines (render tree) of
        first : rest -> first : take 1 (reverse rest)
        [] -> []
    )

-- | The time to render nested flow collections with a comment inside is
-- linear in the depth.
test_deepComment :: Assertion
test_deepComment =
  assertEqual
    "output"
    (Right (T.replicate (depth - 1) "- " <> "[\n" <> indent <> "# c\n" <> indent <> "]\n"))
    (renderSyntax defaultRenderOptions <$> parseDocumentsText (T.replicate depth "[" <> " # c\n" <> T.replicate depth "]\n"))
  where
    depth :: Int
    depth = 100000

    indent :: T.Text
    indent = T.replicate (2 * (depth - 1)) " "

-- | The time to render a double-quoted scalar whose escaped line breaks all
-- join their lines is linear in the number of lines.
test_escapedBreaks :: Assertion
test_escapedBreaks =
  assertEqual
    "output"
    (Right ("k: \"a" <> T.replicate count " b" <> "\\\n  c\"\n"))
    (renderSyntax defaultRenderOptions <$> parseDocumentsText ("k: \"a\\\n" <> T.replicate count "  \\ b\\\n" <> "  c\"\n"))
  where
    count :: Int
    count = 300000

test_forceBlock :: Assertion
test_forceBlock = do
  assertEqual
    "output"
    (Right expected)
    (renderSyntax defaultRenderOptions {forceBlock = True} <$> parseDocumentsText input)
  assertEqual
    "collection in a key"
    (Right "? - a\n  - b\n: 1\n")
    (renderSyntax defaultRenderOptions {forceBlock = True} <$> parseDocumentsText "[a, b]: 1\n")
  where
    input :: T.Text
    input = "list: [a, [b, c], {d: e}]\nkey: [[f]]\n"

    expected :: T.Text
    expected =
      T.unlines
        [ "list:"
        , "- a"
        , "- - b"
        , "  - c"
        , "- d: e"
        , "key:"
        , "- - f"
        ]

-- | A scalar that the source writes on several lines keeps its lines, also
-- where the text has a space in place of a line break.
test_scalarLines :: Assertion
test_scalarLines = do
  rendersBack "folded" "options: >-\n  --health-cmd pg_isready\n  --health-interval 5s\n  --health-retries 10\n"
  rendersBack "folded with paragraphs" "a: >\n  one\n  two\n\n  three\n  four\n"
  rendersBack "folded with more indented lines" "a: >\n  one\n    two\n  three\n  four\n"
  rendersBack "folded with a space at the end of a line" "a: >-\n  one \n  two\n"
  rendersBack "empty block scalars" "a: |-\nb: >-\nc:\n- |-\n"
  rendersAs "empty block scalars with clip" "a: |-\nb: >-\n" "a: |\nb: >\n"
  rendersBack "block scalars of only line breaks" "a: |+\n\nb:\n  c: |+\n\n\n  d: 1\n"
  rendersBack "block scalar of only line breaks at the top level" "|+\n\n"
  rendersBack "plain" "a: one\n  two\n  three\n"
  rendersBack "plain with an empty line" "a: one\n\n  two\n"
  rendersBack "plain in a sequence" "- one\n  two\n"
  rendersBack "plain root" "one\n  two\n"
  rendersBack "plain in a flow sequence" "a: [one\n  two, three]\n"
  rendersBack "single-quoted" "a: 'one\n  two'\n"
  rendersBack "double-quoted" "a: \"one\n  two\"\n"
  rendersBack "double-quoted with an escaped line break" "a: \"one\\\n  two\"\n"
  rendersBack "double-quoted with an empty line" "a: \"one\n\n  two\"\n"
  rendersBack "comment after the last line" "a: one\n  two # c\n"
  rendersAs "key" "one two: a\n" "? one\n  two\n: a\n"
  rendersAs "indentation" "a: one\n  two\n" "a:   one\n      two\n"
  let folded :: String -> [T.Text] -> Assertion
      folded preface ls = do
        let out = render (mappingNode [(plainNode "a", foldedNode ls)])
        assertEqual preface ("a: >-\n" <> T.concat [if T.null l then "\n" else "  " <> l <> "\n" | l <- ls]) out
        assertEqual
          (preface ++ ", read back")
          (Right [[(foldedNode ls).content]])
          (map (\d -> [v.content | MappingContent _ kvs <- [d.root.content], (_, v) <- kvs]) <$> parseDocumentsText out)
  folded "folded node" ["one two", "three", "four"]
  folded "folded node with a space at a line start" ["one", " two", "three"]
  folded "folded node with a space at a line end" ["one ", "two"]
  folded "folded node with one line" ["one"]
  folded "folded node with empty lines" ["one", "", "two", "", "", "three"]
  folded "folded node with an indented example" ["Example:", "  GET /orders", "", "The end."]
  assertEqual
    "positions"
    (Right [ScalarLinesContent Plain "one two\nthree" [4, 8]])
    (map (\d -> d.root.content) <$> parseDocumentsText "one\n two\n\n three\n")

test_documents :: Assertion
test_documents = do
  rendersBack "markers" $
    T.unlines
      [ "first"
      , "---"
      , "second"
      , "..."
      , "%YAML 1.2"
      , "---"
      , "a: b"
      , "---"
      ]
  -- YAML 1.1 parsers need a start marker after an end marker.
  rendersAs "document after an end marker" "a\n...\n---\nb\n" "a\n...\nb\n"
  rendersAs "comment after the end marker" "a: b\n...\n# c\n---\nd: e\n" "a: b\n...\n# c\nd: e\n"
  rendersBack "comment before the directives" "a\n...\n# b\n%YAML 1.2\n---\nc\n"
  rendersBack "comments at the end of a root collection and a document" "a: 1\n# b\n\n# c\n...\n"
  rendersBack "comments around an end marker between documents" "a\n# b\n...\n# c\n---\nd\n"
  rendersAs
    "empty line before the bracket of a flow root"
    "key: value\n# zq\n...\n"
    "{\n key: value\n # zq\n\n}\n...\n"
  rendersAs
    "empty line before the bracket of a flow value"
    "a:\n  key: value\n  # zq\n\nb: 1\n"
    "a: {\n key: value\n # zq\n\n }\nb: 1\n"
  rendersAs
    "empty line before the bracket and a comment after it"
    "a: {key: value} # c\n\nb: 1\n"
    "a: {\n key: value\n\n } # c\nb: 1\n"
  assertEqual
    "comment after a byte order mark between documents"
    (Right [[("document", "after", "c")], [("document", "before", "d")]])
    (map commentsOf <$> parseDocumentsText "a: 1\n...\n\xFEFF# c\n\n\xFEFF# d\n---\nb: 2\n")
  let commented :: Document -> Document
      commented d = d {docComments = noComments {before = [Comment "c"]}}
  assertEqual
    "comment above a document without an end marker above it"
    "a\n\n# c\n---\nb\n"
    (renderSyntax defaultRenderOptions [document (plainNode "a"), commented (document (plainNode "b"))])
  assertEqual
    "comment above a document with directives"
    "a\n...\n\n# c\n%YAML 1.2\n---\nb\n"
    (renderSyntax defaultRenderOptions [document (plainNode "a"), commented (document (plainNode "b")) {version = Just (YamlVersion 1 2)}])
  let flowWithLines = (document (contentNode (SequenceContent Flow [plainNode "a"]))) {docComments = noComments {after = [Comment "c"]}}
      beforeDirectives = renderSyntax defaultRenderOptions [flowWithLines, (document (plainNode "b")) {version = Just (YamlVersion 1 2)}]
  assertEqual "lines of a flow root above directives" "[a]\n...\n# c\n%YAML 1.2\n---\nb\n" beforeDirectives
  rendersBack "lines of a flow root above directives, rendered again" beforeDirectives
  -- A block scalar without content would take the comment in.
  forM_ [Literal, Folded] $ \style ->
    assertEqual
      ("comment above a document below an empty " ++ show style ++ " root")
      "\"\"\n\n# c\n---\nb\n"
      (renderSyntax defaultRenderOptions [document (scalarNode style ""), commented (document (plainNode "b"))])
  let keyComment :: Document
      keyComment = document (mappingNode [((plainNode "k") {comments = noComments {before = [Comment "c"]}}, plainNode "v")])
      afterEnd :: T.Text
      afterEnd = renderSyntax defaultRenderOptions [(document (plainNode "a")) {explicitEnd = True}, keyComment]
      firstKeyLines :: Document -> [Line]
      firstKeyLines d = case d.root.content of
        MappingContent _ ((k, _) : _) -> k.comments.before
        _ -> []
  assertEqual "comment above the first key after an end marker" "a\n...\n---\n# c\nk: v\n" afterEnd
  assertEqual
    "comment above the first key after an end marker, read back"
    (Right [[], [Comment "c"]])
    (map firstKeyLines <$> parseDocumentsText afterEnd)
  let rootWithGap :: Bool -> Document
      rootWithGap end =
        (document (contentNode (SequenceContent Block [plainNode "a"])) {comments = noComments {after = [Comment "c", EmptyLine]}})
          { explicitEnd = end
          }
  assertEqual "empty line at the end of a block root before an end marker" "- a\n# c\n\n...\n" (renderSyntax defaultRenderOptions [rootWithGap True])
  assertEqual
    "empty line at the end of a block root before a document"
    "- a\n# c\n\n---\nb\n"
    (renderSyntax defaultRenderOptions [rootWithGap False, document (plainNode "b")])
  -- The end marker keeps the lines of a document from the next document.
  rendersBack "empty line below a flow root above an end marker" "[a]\n\n# c\n...\n---\nx\n"
  rendersBack "empty line at the end of a flow root above an end marker" "[a]\n# c\n\n...\n---\nx\n"
  rendersAs "empty line at the end of a flow root in the block style" "key: value\n\n# c\n...\n---\nx\n" "{\n key: value\n\n# c\n}\n---\nx\n"
  let boundary :: String -> T.Text -> [[(String, String, T.Text)]] -> [Document] -> Assertion
      boundary preface expected comments docs = do
        let rendered = renderSyntax defaultRenderOptions docs
        assertEqual preface expected rendered
        assertEqual (preface ++ ", read back") (Right comments) (map commentsOf <$> parseDocumentsText rendered)
      withLines :: Comments -> Node -> Node
      withLines c n = n {comments = c}
  boundary
    "empty line at the end of a block root before a document"
    "k: v\n\n# c\n...\n---\nb\n"
    [[("", "after", "c")], []]
    [document (withLines noComments {after = [EmptyLine, Comment "c"]} (mappingNode [(plainNode "k", plainNode "v")])), document (plainNode "b")]
  boundary
    "empty line at the end of the last value of a block root before a document"
    "k: v\n\n# c\n...\n---\nb\n"
    [[("", "after", "c")], []]
    [ document (withLines noComments {after = [Comment "c"]} (mappingNode [(plainNode "k", withLines noComments {after = [EmptyLine]} (plainNode "v"))]))
    , document (plainNode "b")
    ]
  boundary
    "empty line below a flow root before a document"
    "[a]\n\n# c\n...\n---\nb\n"
    [[("document", "after", "c")], []]
    [ (document (contentNode (SequenceContent Flow [plainNode "a"]))) {docComments = noComments {after = [EmptyLine, Comment "c"]}}
    , document (plainNode "b")
    ]
  boundary
    "empty line after the last key of a block root before a document"
    "k: v\n\n  # c\n...\n---\nb\n"
    [[("/k", "after", "c")], []]
    [document (mappingNode [(withLines noComments {after = [EmptyLine, Comment "c"]} (plainNode "k"), plainNode "v")]), document (plainNode "b")]
  boundary
    "empty line above the comment of an empty root before a document"
    "a\n---\n\n# c\n...\n---\nb\n"
    [[], [("", "after", "c")], []]
    [document (plainNode "a"), document (withLines noComments {before = [EmptyLine, Comment "c"]} (plainNode "")), document (plainNode "b")]
  boundary
    "keep literal root above a comment of the next document"
    "|+\n  a\n\n...\n\n# c\n---\nb\n"
    [[], [("document", "before", "c")]]
    [document (scalarNode Literal "a\n\n"), commented (document (plainNode "b"))]
  boundary
    "keep literal at the end of a root above a comment of the next document"
    "k: |+\n  a\n\n...\n\n# c\n---\nb\n"
    [[], [("document", "before", "c")]]
    [document (mappingNode [(plainNode "k", scalarNode Literal "a\n\n")]), commented (document (plainNode "b"))]
  let versioned :: YamlVersion -> T.Text
      versioned v = renderSyntax defaultRenderOptions [(document (plainNode "a")) {version = Just v}]
  assertEqual "supported version" "%YAML 1.3\n---\na\n" (versioned (YamlVersion 1 3))
  assertEqual "unsupported version" "a\n" (versioned (YamlVersion 2 0))
  assertEqual "negative minor version" "a\n" (versioned (YamlVersion 1 (-1)))
  assertEqual "minor version beyond the limit" "a\n" (versioned (YamlVersion 1 1000001))
  -- Without the marker, the next parse would give the comment to the root.
  let first :: String -> T.Text -> Node -> Assertion
      first preface expected root = do
        let out = renderSyntax defaultRenderOptions [commented (document root)]
        assertEqual preface expected out
        assertEqual (preface ++ ", read back") (Right [[Comment "c"]]) (map (\d -> d.docComments.before) <$> parseDocumentsText out)
  first "comment above the first document" "# c\n---\na: 1\n" (mappingNode [(plainNode "a", plainNode "1")])
  first "comment above the first document with a scalar root" "# c\n---\na\n" (plainNode "a")

-- | The comments of a document with the path of their nodes.
commentsOf :: Document -> [(String, String, T.Text)]
commentsOf doc = lines_ "document" doc.docComments ++ node "" doc.root
  where
    node :: String -> Node -> [(String, String, T.Text)]
    node path n = lines_ path n.comments {after = []} ++ inner ++ lines_ path noComments {after = n.comments.after}
      where
        inner :: [(String, String, T.Text)]
        inner = case n.content of
          SequenceContent _ xs -> concat (zipWith (\i x -> node (path ++ "/" ++ show i) x) [0 :: Int ..] xs)
          MappingContent _ kvs -> concatMap (entry path) kvs
          _ -> []

    entry :: String -> (Node, Node) -> [(String, String, T.Text)]
    entry path (k, v) =
      let path' = path ++ "/" ++ keyText k
      in node (path' ++ ":key") k ++ node path' v

    keyText :: Node -> String
    keyText k = case k.content of
      ScalarContent _ t -> T.unpack t
      _ -> "?"

    lines_ :: String -> Comments -> [(String, String, T.Text)]
    lines_ path c =
      [(path, "before", t) | Comment t <- c.before]
        ++ [(path, "inline", t) | Just t <- [c.inline]]
        ++ [(path, "after", t) | Comment t <- c.after]

-- | Each rule of the documentation.
test_attachment :: Assertion
test_attachment = do
  let check :: String -> [(String, String, T.Text)] -> T.Text -> Assertion
      check preface expected input = case parseDocumentsText input of
        Right [doc] -> assertEqual preface expected (commentsOf doc)
        r -> assertFailure (preface ++ ": " ++ show r)
  check "above a key" [("/b:key", "before", "c")] "a: 1\n# c\nb: 2\n"
  check "above the first key" [("/a:key", "before", "c")] "# c\na: 1\n"
  check "above the first key of a value" [("/a/b:key", "before", "c")] "a:\n  # c\n  b: 1\n"
  check "above an empty line above the first key" [("", "before", "c"), ("/a:key", "before", "d")] "# c\n\n# d\na: 1\n"
  check "above the first key after an indicator" [("/0", "inline", "c"), ("/0/a:key", "before", "d")] "- # c\n  # d\n  a: 1\n"
  check "above an item with a mapping" [("/0", "before", "c"), ("/1", "before", "d")] "# c\n- a: 1\n# d\n- b: 2\n"
  check "at the end of a value" [("/a", "inline", "c")] "a: 1 # c\n"
  check "at the end of a key" [("/a:key", "inline", "c")] "a: # c\n  b: 1\n"
  check "on a block scalar header" [("/a", "inline", "c")] "a: | # c\n  text\n"
  check "after a block scalar in a key" [("/?:key/0", "inline", "c"), ("/?", "inline", "d")] "? - | # c\n    text\n: # d\n  - x\n"
  check "after a kept block scalar in a key" [("/?", "inline", "c")] "? - |+\n    text\n\n: # c\n  k: v\n"
  check "above a sequence item" [("/a/1", "before", "c")] "a:\n- 1\n# c\n- 2\n"
  check "after a flow collection" [("/a", "inline", "c")] "a: [1, 2] # c\n"
  check "on an item line" [("/0", "inline", "c")] "- # c\n  a: 1\n"
  check "on an item line and after the item" [("/0", "before", "c"), ("/0", "inline", "d")] "- # c\n  a # d\n"
  check "on a bracket line and after the item" [("/a/0", "before", "c"), ("/a/0", "inline", "d")] "a: [ # c\n  1, # d\n  2]\n"
  check "on an item line and on a block scalar header" [("/0", "before", "c"), ("/0", "inline", "d")] "- # c\n  | # d\n  text\n"
  check "at the end of an indented list" [("/a", "after", "c")] "a:\n  - 1\n  # c\nb: 2\n"
  check "at the key column after a list" [("/b:key", "before", "c")] "a:\n- 1\n# c\nb: 2\n"
  check "at the end of a nested mapping" [("/a", "after", "c")] "a:\n  b: 1\n  # c\nd: 2\n"
  check "at the end of the root" [("", "after", "c")] "a: 1\n# c\n"
  check "after an empty line at the end of the root" [("", "after", "c"), ("", "after", "d")] "a: 1\n# c\n\n# d\n"
  check "at the end of a scalar root" [("", "after", "c")] "a\n# c\n"
  check "below a flow root" [("document", "after", "c")] "[a]\n# c\n"
  check "before the end marker" [("document", "after", "d"), ("", "after", "c")] "a\n# c\n...\n# d\n"
  check "below a flow root and the end marker" [("document", "after", "c"), ("document", "after", "d")] "[a]\n# c\n...\n# d\n"
  check "before the marker" [("document", "before", "c")] "# c\n---\na: 1\n"
  check "on the marker line" [("document", "inline", "c")] "--- # c\na: 1\n"
  check "after a root on the marker line" [("", "inline", "c")] "--- a # c\n"
  check "after a tag on the marker line" [("document", "inline", "c")] "--- !!map # c\na: 1\n"
  check "after the end marker" [("document", "after", "c")] "a\n...\n# c\n"
  check "after the end marker of a mapping" [("document", "after", "c")] "a: 1\n...\n# c\n"
  check "on the end marker line" [("document", "after", "c")] "a\n... # c\n"
  check "after two end markers" [("document", "after", "c"), ("document", "after", "d")] "a\n...\n# c\n...\n# d\n"
  check "on a second end marker line" [("document", "after", "c")] "a\n...\n... # c\n"
  check "after an empty flow sequence with lines inside" [("/0", "inline", "d"), ("/0", "after", "c")] "- [\n  # c\n  ] # d\n- 2\n"
  check "after a flow mapping with lines inside" [("/k", "inline", "d"), ("/k", "after", "c")] "k: {a: 1,\n  # c\n  } # d\n"
  check "inside a flow sequence" [("/0", "inline", "c"), ("/1", "before", "d")] "[a, # c\n # d\n b]\n"
  check "below an explicit key without a value" [("/b:key", "before", "c")] "? a\n# c\n? b\n"
  check "at the end of a list item with an explicit key" [("/0", "after", "c")] "- ? a\n  # c\n- b\n"
  check "at the end of a mapping with an explicit key" [("/x", "after", "c")] "x:\n  ? a\n  # c\ny: 1\n"
  check "empty lines" [] "a: 1\n\n\nb: 2\n"
  assertEqual
    "empty lines"
    (Right [EmptyLine, EmptyLine])
    ((\case [d] | MappingContent _ [_, (k, _)] <- d.root.content -> k.comments.before; _ -> []) <$> parseDocumentsText "a: 1\n\n\nb: 2\n")
  assertEqual
    "empty line below the end of a collection"
    (Right [([Comment "c"], [EmptyLine])])
    ( map
        ( \d -> case d.root.content of
            MappingContent _ [(_, v), (k, _)] -> (v.comments.after, k.comments.before)
            _ -> ([], [])
        )
        <$> parseDocumentsText "a:\n  b: 1\n  # c\n\nd: 2\n"
    )
  assertEqual
    "empty line below an explicit key without a value"
    (Right "a:\n\n# c\nb:\n")
    (renderSyntax defaultRenderOptions <$> parseDocumentsText "? a\n\n# c\n? b\n")
  assertEqual
    "empty line at the end of the root"
    (Right [([Comment "c"], [EmptyLine, Comment "d"], [])])
    ( map
        ( \d -> case d.root.content of
            MappingContent _ [(_, v)] -> (v.comments.after, d.root.comments.after, d.docComments.after)
            _ -> ([], [], [])
        )
        <$> parseDocumentsText "a:\n  b: 1\n  # c\n\n# d\n"
    )
  let between :: String -> [([Line], [Line])] -> T.Text -> Assertion
      between preface expected input =
        assertEqual
          preface
          (Right expected)
          (map (\d -> (d.root.comments.after ++ d.docComments.after, d.docComments.before ++ d.root.comments.before)) <$> parseDocumentsText input)
  between
    "above the marker of the next document"
    [([Comment "c"], []), ([], [])]
    "a\n# c\n---\nb\n"
  between
    "empty line above the marker of the next document"
    [([Comment "c"], []), ([], [EmptyLine, Comment "d"])]
    "a\n# c\n\n# d\n---\nb\n"
  between
    "empty line after the end marker"
    [([Comment "c"], []), ([], [EmptyLine, Comment "d"])]
    "a\n...\n# c\n\n# d\n---\nb\n"
  between
    "empty line after the end marker above a bare document"
    [([Comment "c"], []), ([], [EmptyLine, Comment "d"])]
    "a\n...\n# c\n\n# d\nb\n"
  between
    "empty line below a flow root"
    [([Comment "c"], []), ([], [EmptyLine, Comment "d"])]
    "[a]\n# c\n\n# d\n---\nb\n"
  between
    "empty line below a flow root above the last end marker"
    [([Comment "c", EmptyLine], [])]
    "[a]\n# c\n\n...\n\n"
  assertEqual
    "empty lines above the first key"
    (Right [([Comment "a", EmptyLine, Comment "b", EmptyLine, EmptyLine], [Comment "c"])])
    (map (\d -> (d.root.comments.before, firstKey d.root)) <$> parseDocumentsText "# a\n\n# b\n\n\n# c\nk: v\n")
  where
    firstKey :: Node -> [Line]
    firstKey n = case n.content of
      MappingContent _ ((k, _) : _) -> k.comments.before
      _ -> []

-- | The parser returns documents with comments without thunks, as it does for
-- documents without comments.
test_noThunks :: Assertion
test_noThunks =
  mapM_
    check
    [ ("configuration", configuration)
    , ("flow collections", "a: [1, # b\n  2] # c\nd: {e: f, # g\n  h: i}\n")
    , ("explicit keys", "? a\n# b\n? c\n: d\n\n# e\n")
    , ("documents", "# a\n--- # b\nc\n...\n# d\n---\ne: 1\n")
    , ("empty quoted keys", "'': a\n? \"\"\n: b\nc: {'': d}\n")
    , ("pairs in flow sequences", "[[]: a, '': b]\n")
    , ("empty nodes", "a:\nb: !t\n? c\nd: {e: , &f : g}\n")
    ]
  where
    check :: (String, T.Text) -> Assertion
    check (preface, input) = case parseDocumentsText input of
      Right docs -> thunks docs >>= assertEqual preface []
      Left e -> assertFailure (preface ++ ": " ++ show e)

prop_noThunks :: Tree -> Property
prop_noThunks (Tree doc) =
  let out = renderSyntax defaultRenderOptions [doc]
  in counterexample (T.unpack out) $ case parseDocumentsText out of
       Right docs -> ioProperty ((=== []) <$> thunks docs)
       Left e -> counterexample (show e) False

-- | The configuration of the haskell-gha test with comments.
test_configuration :: Assertion
test_configuration = case parseDocumentsText configuration of
  Right [doc] -> assertEqual "comments" expected (commentsOf doc)
  r -> assertFailure (show r)
  where
    expected :: [(String, String, T.Text)]
    expected =
      [ ("/matrix:key", "before", "The oldest and the newest supported Postgres.")
      , ("/services:key", "before", "The services of each build job.")
      , ("/services/postgres:key", "before", "The database for the tests.")
      , ("/services/postgres/env/POSTGRES_PASSWORD", "inline", "Only for CI.")
      , ("/permissions:key", "before", "The test reporter writes check runs.")
      , ("/permissions/checks:key", "before", "For the annotations of the test results.")
      , ("/hooks:key", "before", "The steps for Postgres.")
      , ("/hooks/before-build/1", "before", "Wait until the database accepts connections.")
      , ("/hooks/before-build", "after", "The database is ready for the build.")
      , ("/hooks/after-build", "after", "The tests come next.")
      ]

configuration :: T.Text
configuration =
  T.unlines
    [ "name: Postgres CI"
    , "branches: [master, 'release/**']"
    , "# The oldest and the newest supported Postgres."
    , "matrix:"
    , "  postgres: ['15', '18']"
    , "  exclude:"
    , "    - ghc: '9.10'"
    , "      postgres: '15'"
    , "apt: [libpq-dev, postgresql-client]"
    , "# The services of each build job."
    , "services:"
    , "  # The database for the tests."
    , "  postgres:"
    , "    image: postgres:${{ matrix.postgres }}"
    , "    env:"
    , "      POSTGRES_PASSWORD: postgres # Only for CI."
    , "    ports: ['5432:5432']"
    , "# The test reporter writes check runs."
    , "permissions:"
    , "  contents: read"
    , "  # For the annotations of the test results."
    , "  checks: write"
    , "# The steps for Postgres."
    , "hooks:"
    , "  before-build:"
    , "    - name: Show the Postgres version"
    , "      run: psql --version"
    , "    # Wait until the database accepts connections."
    , "    - name: Wait for Postgres"
    , "      run: |"
    , "        until pg_isready -h localhost; do"
    , "          sleep 1"
    , "        done"
    , "    # The database is ready for the build."
    , "  after-build:"
    , "    - name: Show the executables"
    , "      run: cabal list-bin all"
    , "    # The tests come next."
    , "ghc-options: -Werror -Wno-unused-imports"
    , "jobs: 2"
    ]

-- | Rendering keeps every comment, and a second round trip gives the same
-- text. The end comments of an indentless sequence belong to its last item
-- after the round trip.
test_commentRoundTrip :: Assertion
test_commentRoundTrip = case parseDocumentsText configuration of
  Right docs -> do
    let out = renderSyntax defaultRenderOptions docs
        texts :: Document -> [T.Text]
        texts d = [t | (_, _, t) <- commentsOf d]
    case parseDocumentsText out of
      Right docs' -> do
        assertEqual ("comments\n" ++ T.unpack out) (map texts docs) (map texts docs')
        assertEqual "text" out (renderSyntax defaultRenderOptions docs')
      Left err -> assertFailure (T.unpack out ++ "\n" ++ show err)
  Left err -> assertFailure (show err)

-- | A comment on a line of its own keeps its # characters. A comment at the
-- end of a line keeps them in its text.
test_hashes :: Assertion
test_hashes = do
  let input = "## a\n### b ###\n####\n# #c\nk: 1 ##d\n  ## e\n"
  assertEqual
    "lines"
    (Right [[CommentLine 2 "a", CommentLine 3 "b ###", CommentLine 4 "", Comment "#c"]])
    (map ((\case MappingContent _ ((k, _) : _) -> k.comments.before; _ -> []) . (.root.content)) <$> parseDocumentsText input)
  assertEqual
    "inline and below a value"
    (Right [(Just "#d", [CommentLine 2 "e"])])
    (map ((\case MappingContent _ [(_, v)] -> (v.comments.inline, v.comments.after); _ -> (Nothing, [])) . (.root.content)) <$> parseDocumentsText input)
  assertEqual "rendered" (Right "## a\n### b ###\n####\n# #c\nk: 1 # #d\n  ## e\n") (renderSyntax defaultRenderOptions <$> parseDocumentsText input)
  assertEqual "count below 1" "# a\n---\nk: 1\n" (renderSyntax defaultRenderOptions [(document (mappingNode [(plainNode "k", plainNode "1")])) {docComments = noComments {before = [CommentLine (-1) "a"]}}])

-- | The lines after a list under a key stay at the end of the list. Without
-- indentation, a block collection as the last item would take them in.
test_linesAfterList :: Assertion
test_linesAfterList = do
  rendersBack "mapping as the last item" "a:\n  - b: 1\n  # c\n"
  rendersBack "list as the last item" "a:\n  - - b\n  # c\n"
  rendersBack "block scalar as the last item" "a:\n  - |\n    b\n  # c\n"
  rendersBack "scalar as the last item" "a:\n- b\n  # c\n"
  rendersBack "no lines after the list" "a:\n- b: 1\n"

-- | The lines above and below the indicator of a block collection with
-- properties stay with their nodes. Above the indicator of a first entry,
-- the collection around it would take the lines up to the last empty line.
test_linesBelowIndicator :: Assertion
test_linesBelowIndicator = do
  let check :: String -> T.Text -> Assertion
      check preface input = case parseDocumentsText input of
        Right docs -> do
          let out = renderSyntax defaultRenderOptions docs
          case parseDocumentsText out of
            Right docs' -> do
              assertEqual (preface ++ "\n" ++ T.unpack out) (map commentsOf docs) (map commentsOf docs')
              assertEqual preface out (renderSyntax defaultRenderOptions docs')
            Left err -> assertFailure (preface ++ ": " ++ show err)
        Left err -> assertFailure (preface ++ ": " ++ show err)
  check "first item with a tag" "k:\n- !!map\n  # a\n\n  # b\n  c: 1\n- d\n"
  check "first item with a comment" "k:\n- &x # a\n  # b\n\n  c: 1\n- d\n"
  check "explicit key" "- ? &x\n    # a\n\n    b: 1\n  : c\n"
  check "nested first items" "- &x\n  - &y\n    # a\n\n    b: 1\n"
  check "second item" "k:\n- a\n- !!map\n  # b\n  c: 1\n"
  check "second item with a comment" "- a\n- &x # a\n  # b\n  c: 1\n"
  let owners :: String -> [(String, String, T.Text)] -> T.Text -> Assertion
      owners preface expected input =
        assertEqual preface (Right [expected]) (map commentsOf <$> parseDocumentsText input)
      ownersRenderBack :: String -> [(String, String, T.Text)] -> T.Text -> Assertion
      ownersRenderBack preface expected input = owners preface expected input >> check preface input
  ownersRenderBack "below the indicator of a second item" [("/jobs/1/name:key", "before", "c")] "jobs:\n- name: a\n- &b\n  # c\n  name: b\n"
  -- The lines of the first entries read back the same above the indicator,
  -- where they stay.
  ownersRenderBack "above a first item with an anchor" [("/jobs/0/name:key", "before", "c")] "jobs:\n# c\n- &b\n  name: b\n"
  rendersBack "above a first item with an anchor, the text" "jobs:\n# c\n- &b\n  name: b\n"
  rendersBack "above nested first items with tags" "# c\n- !a\n  - !b\n    - 2\n"
  rendersBack "above a second item with nested first items" "- x\n# c\n- !a\n  - !b\n    - 2\n"
  rendersBack "above an explicit key with an anchor" "# c\n? &a\n  - a\n: b\n"
  rendersBack "below a first item with a comment on its line" "- &a # i\n  # c\n  k: v\n"
  -- A comment on the line of the indicator keeps the lines above it from
  -- the first entries.
  rendersBack "above a first item with a comment and nested first items" "# c\n- # d\n  - !!map\n    k: v\n"
  rendersBack "above a second item with a comment and nested first items" "- x\n# c\n\n# e\n- # d\n  - &b\n    - y\n"
  rendersBack "above a first item with a comment" "# c\n- # d\n  # f\n  - a\n"
  rendersBack "above a first item with a comment under a key" "k:\n# c\n- # d\n  - a\n"
  rendersBack "above an explicit key with a comment" "# c\n? # d\n  - a\n: v\n"
  rendersBack "below an indicator above a first item with a comment" "- # a\n  # h\n  - # b\n    - x\n"
  rendersBack "below properties above a first item with a comment" "- !!seq\n  # h\n  - # b\n    - x\n"
  rendersBack "below an indicator above an explicit key with a comment" "- # a\n  # h\n  ? # b\n    - x\n  : v\n"
  rendersBack "below root properties above a first item with a comment" "!!seq\n# h\n- # b\n  - x\n"
  -- A collection on the line of its indicator would take the lines of its
  -- first entry, so it starts below the indicator.
  ownersRenderBack "above a nested first item" [("/0/0", "before", "c")] "# c\n-\n  - 1\n"
  rendersBack "above a nested first item, the text" "# c\n-\n  - 1\n"
  ownersRenderBack "above a first key" [("/1/a:key", "before", "c")] "- x\n# c\n-\n  a: 1\n  b: 2\n"
  rendersBack "above a first key, the text" "- x\n# c\n-\n  a: 1\n  b: 2\n"
  rendersAs "above an explicit key" "- ?\n    # c\n    - a\n  : v\n" "-\n  ?\n    # c\n    - a\n  : v\n"
  ownersRenderBack "below the indicator of a scalar" [("/1", "before", "c")] "- a\n- !!str\n  # c\n  x\n"
  ownersRenderBack "below the indicator of an explicit key" [("/x:key", "before", "c")] "k: a\n? &k\n  # c\n  x\n: v\n"
  ownersRenderBack "below the indicator of an explicit value" [("/?/b:key", "before", "c")] "? a: 1\n: &x\n  # c\n  b: 2\n"
  ownersRenderBack
    "below an indicator with a comment"
    [("/1", "inline", "i"), ("/1/c:key", "before", "b")]
    "- a\n- # i\n  # b\n  c: 1\n"
  -- The renderer writes these items on the line of the indicator, with the
  -- lines above it, so the lines read back as the lines of the item.
  owners "below a bare indicator" [("/1/name:key", "before", "c")] "-\n  name: a\n-\n  # c\n  name: b\n"
  owners "below the indicator of a nested list" [("/1/0", "before", "c")] "- - a\n-\n  # c\n  - x\n"
  let withAbove :: Node -> Node
      withAbove n = n {comments = noComments {before = [Comment "a"]}}
      list :: Node
      list = sequenceNode [plainNode "1"]
  assertEqual
    "lines of a first item below its indicator"
    (Right [[("/0", "before", "a"), ("/0", "inline", "i")]])
    (map commentsOf <$> parseDocumentsText (render (sequenceNode [list {comments = noComments {before = [Comment "a"], inline = Just "i"}}])))
  let anchored :: Node -> Node
      anchored n = n {props = noProps {anchor = Just "x"}}
  assertEqual
    "lines of a first item with nested first items"
    (Right [[("/0", "before", "a")]])
    (map commentsOf <$> parseDocumentsText (render (sequenceNode [withAbove (anchored (sequenceNode [anchored list]))])))
  assertEqual "lines of a block value below its key" "k:\n# a\n\n- 1\n" (render (mappingNode [(plainNode "k", withAbove list)]))
  assertEqual
    "lines of a block value below its key read back"
    (Right [[("/k", "before", "a")]])
    (map commentsOf <$> parseDocumentsText (render (mappingNode [(plainNode "k", withAbove list)])))

-- | A comment without a place at its node moves to one that has it.
test_movedComments :: Assertion
test_movedComments = do
  let withInline :: T.Text -> Node -> Node
      withInline t n = n {comments = n.comments {inline = Just t}}
      withBefore :: T.Text -> Node -> Node
      withBefore t n = n {comments = n.comments {before = [Comment t]}}
      withAfter :: T.Text -> Node -> Node
      withAfter t n = n {comments = n.comments {after = [Comment t]}}
  assertEqual
    "lines above a value on the line of the key"
    "# v\na: 1\n"
    (render (mappingNode [(plainNode "a", withBefore "v" (plainNode "1"))]))
  assertEqual
    "lines after a scalar key"
    "# b\nk: 1\n  # a\n"
    (render (mappingNode [(withAfter "a" (withBefore "b" (plainNode "k")), plainNode "1")]))
  assertEqual
    "lines after a scalar key with a block scalar value"
    "# a\nk: |\n  text\n"
    (render (mappingNode [(withAfter "a" (plainNode "k"), contentNode (ScalarContent Literal "text\n"))]))
  assertEqual
    "lines after a block scalar value"
    "k: |\n  text\n# a\nx: 1\n"
    (render (mappingNode [(plainNode "k", withAfter "a" (contentNode (ScalarContent Literal "text\n"))), (plainNode "x", plainNode "1")]))
  assertEqual
    "lines after a list item"
    "- 1\n  # a\n- 2\n"
    (render (contentNode (SequenceContent Block [withAfter "a" (plainNode "1"), plainNode "2"])))
  assertEqual
    "empty lines at the end of an empty flow collection"
    "a: [\n  # c\n  ]\n\nb: 1\n"
    ( render
        ( mappingNode
            [ (plainNode "a", (contentNode (SequenceContent Flow [])) {comments = noComments {after = [Comment "c", EmptyLine]}})
            , (plainNode "b", plainNode "1")
            ]
        )
    )
  assertEqual
    "two comments on one line"
    "# k\na: 1 # v\n"
    (render (mappingNode [(withInline "k" (plainNode "a"), withInline "v" (plainNode "1"))]))
  assertEqual
    "comment in a flow sequence"
    "a:\n- 1 # c\n- 2\n"
    (render (mappingNode [(plainNode "a", contentNode (SequenceContent Flow [withInline "c" (plainNode "1"), plainNode "2"]))]))
  assertEqual
    "YAML 1.1 line breaks in comments"
    "# a\n# b\n# c\n# d\nk: v # e f g h\n"
    ( render
        ( mappingNode
            [(withBefore "a\x85\&b\x2028\&c\x2029\&d" (plainNode "k"), withInline "e\x85\&f\x2028\&g\x2029\&h" (plainNode "v"))]
        )
    )
  assertEqual
    "comment on a block root"
    "--- # c\na: 1\n"
    (render (withInline "c" (mappingNode [(plainNode "a", plainNode "1")])))
  rendersBack "comment on the properties of a block root" "# r\n!!map # c\n# f\na: 1\n"
  rendersBack "comment on the properties of a block root below a marker with a comment" "--- # d\n&a # c\n- x\n"
  rendersAs
    "lines below the properties of a block root with a comment"
    "# e\n\n!!map # c\n# f\na: 1\n"
    "!!map # c\n# e\n\n# f\na: 1\n"
  let rootWithLines = withBefore "r" (mappingNode [(plainNode "a", plainNode "1")])
  assertEqual "lines of a block root without an empty line" "# r\n\na: 1\n" (render rootWithLines)
  assertEqual
    "lines of a block root read back"
    (Right [[Comment "r", EmptyLine]])
    (map (\d -> d.root.comments.before) <$> parseDocumentsText (render rootWithLines))
  assertEqual
    "comment on a block root below the comment of the marker"
    "--- # d\n# c\n\na: 1\n"
    ( renderSyntax
        defaultRenderOptions
        [ (document (withInline "c" (mappingNode [(plainNode "a", plainNode "1")])))
            { docComments = noComments {inline = Just "d"}
            }
        ]
    )
  let list :: Node -> Node
      list item =
        mappingNode
          [ (plainNode "a", withAfter "c" (sequenceNode [item]))
          , (plainNode "b", plainNode "2")
          ]
  assertEqual
    "end of a list with a mapping"
    "a:\n  - x: 1\n  # c\nb: 2\n"
    (render (list (mappingNode [(plainNode "x", plainNode "1")])))
  assertEqual
    "end of a list with a block scalar"
    "a:\n  - |\n    x\n  # c\nb: 2\n"
    (render (list (scalarNode Literal "x\n")))

-- | Rendering a tree and parsing the result gives the same tree, except for
-- the styles, the offsets and the places of the comments. Every comment
-- stays, and rendering the result again gives the same text.
prop_roundTrip :: Tree -> Property
prop_roundTrip (Tree doc) =
  let out = renderSyntax defaultRenderOptions [doc]
  in counterexample (T.unpack out) $ case parseDocumentsText out of
       Right [doc'] ->
         checkCoverage . cover 10 (hasLines doc'.root) "scalars on several lines" $
           conjoin
             [ counterexample "tree" $ strip doc'.root === strip (flowItems False doc.root)
             , counterexample "comments" $ L.sort (allComments doc') === L.sort (allComments doc)
             , let out' = renderSyntax defaultRenderOptions [doc']
               in counterexample ("text: " ++ firstDifference out out') (out' == out)
             ]
       r -> counterexample (show r) False
  where
    strip :: Node -> Node
    strip n =
      ( contentNode $ case n.content of
          ScalarContent _ t -> ScalarContent Plain t
          SequenceContent _ xs -> SequenceContent Block (map strip xs)
          MappingContent _ kvs -> MappingContent Block [(strip k, strip v) | (k, v) <- kvs]
          AliasContent a -> AliasContent a
      )
        { props = n.props
        }

    -- The first line where two texts differ, with the line before it.
    firstDifference :: T.Text -> T.Text -> String
    firstDifference a b = go 1 "" (T.lines a) (T.lines b)
      where
        go :: Int -> T.Text -> [T.Text] -> [T.Text] -> String
        go n prev xs ys = case (xs, ys) of
          (x : xs', y : ys') | x == y -> go (n + 1) x xs' ys'
          _ ->
            "line "
              ++ show n
              ++ " after "
              ++ show prev
              ++ ": "
              ++ show (take 1 xs)
              ++ " /= "
              ++ show (take 1 ys)

    allComments :: Document -> [T.Text]
    allComments d = [t | (_, _, t) <- commentsOf d]

    hasLines :: Node -> Bool
    hasLines n = case n.content of
      ScalarLinesContent _ _ starts -> not (null starts)
      SequenceContent _ xs -> any hasLines xs
      MappingContent _ kvs -> any (\(k, v) -> hasLines k || hasLines v) kvs
      AliasContent _ -> False

    -- The renderer gives an empty item of a flow sequence a tag.
    flowItems :: Bool -> Node -> Node
    flowItems inFlow n = case n.content of
      SequenceContent s xs ->
        let inFlow' = inFlow || (s == Flow && not (hasComments n))
        in n {content = SequenceContent s (map (item inFlow' . flowItems inFlow') xs)}
      MappingContent s kvs ->
        let inFlow' = inFlow || (s == Flow && not (hasComments n))
        in n {content = MappingContent s [(flowItems inFlow' k, flowItems inFlow' v) | (k, v) <- kvs]}
      _ -> n

    item :: Bool -> Node -> Node
    item inFlow n = case (n.props, n.content) of
      (Props Nothing NoTag, ScalarContent Plain "")
        | inFlow ->
            n {props = Props Nothing (Tag "tag:yaml.org,2002:null")}
      _ -> n

    -- A flow collection with comments inside becomes a block collection.
    hasComments :: Node -> Bool
    hasComments n =
      not (null [() | Comment _ <- n.comments.after]) || case n.content of
        SequenceContent _ xs -> any inner xs
        MappingContent _ kvs -> any (\(k, v) -> inner k || inner v) kvs
        _ -> False
      where
        inner :: Node -> Bool
        inner x =
          not (null [() | Comment _ <- x.comments.before])
            || isJust x.comments.inline
            || hasComments x

newtype Tree = Tree Document
  deriving stock (Show)

instance Arbitrary Tree where
  arbitrary = do
    root <- sized genNode
    c <- genComments False
    pure . Tree $ (document root) {docComments = c}

genNode :: Int -> Gen Node
genNode size = do
  n <-
    if size <= 1
      then genScalar
      else
        frequency
          [ (3, genScalar)
          , (1, contentNode . AliasContent <$> genAnchor)
          , (1, contentNode <$> (SequenceContent <$> genStyle <*> genList))
          , (1, contentNode <$> (MappingContent <$> genStyle <*> genEntries))
          ]
  p <- case n.content of
    AliasContent _ -> pure noProps
    _ -> genProps
  c <- genComments (isCollection n)
  pure n {props = p, comments = c}
  where
    genList :: Gen [Node]
    genList = do
      k <- choose (0, 4)
      vectorOf k (genNode (size `div` 3))

    genEntries :: Gen [(Node, Node)]
    genEntries = do
      k <- choose (0, 4)
      vectorOf k ((,) <$> genNode (size `div` 4) <*> genNode (size `div` 3))

    genStyle :: Gen CollectionStyle
    genStyle = elements [Block, Flow]

    isCollection :: Node -> Bool
    isCollection n = case n.content of
      SequenceContent _ (_ : _) -> True
      MappingContent _ (_ : _) -> True
      _ -> False

    -- A scalar, often with positions of new lines. Some positions are not
    -- valid, e.g. outside the text or twice the same.
    genScalar :: Gen Node
    genScalar = do
      style <- elements [minBound .. maxBound]
      t <- genText
      starts <- frequency [(1, pure []), (2, L.sort <$> listOf (choose (0, T.length t + 1)))]
      pure (contentNode (ScalarLinesContent style t starts))

    genProps :: Gen Props
    genProps =
      Props
        <$> oneof [pure Nothing, Just <$> genAnchor]
        <*> elements
          [ NoTag
          , NoTag
          , NonSpecificTag
          , Tag "tag:yaml.org,2002:str"
          , Tag "!local"
          , Tag "tag:example.com,2000:x"
          ]

    genAnchor :: Gen T.Text
    genAnchor = elements ["a", "b", "anchor"]

    genText :: Gen T.Text
    genText =
      oneof
        [ elements tricky
        , T.pack <$> listOf genChar
        , T.intercalate "\n" <$> listOf (T.pack <$> listOf genChar)
        ]
      where
        tricky :: [T.Text]
        tricky =
          [ ""
          , " "
          , "-"
          , "- a"
          , "? a"
          , ": a"
          , "a: b"
          , "a:b"
          , "#"
          , "a #b"
          , "true"
          , "12"
          , "---"
          , "..."
          , "foo\n"
          , "\nfoo"
          , "  lead"
          , "trail  "
          , "a\n\nb\n\n"
          , "\n"
          , "\n\n"
          , " \n"
          , "a\n "
          , "|"
          , ">"
          , "[a]"
          , "{a: b}"
          , "a, b"
          , "key:"
          , "\r\n"
          , "a\n  b\nc"
          , "  a\nb"
          , "a\n\n  b\n\nc\n"
          ]

        genChar :: Gen Char
        genChar =
          frequency
            [ (10, elements "abc xyz-:#,[]{}'\"!&*?|>%@`\\")
            , (2, elements "\t\r\x85\xA0\x2028\xFEFF\x01")
            , (1, arbitrary)
            ]

-- | Comments for a node. Only a non-empty collection has lines after it.
genComments :: Bool -> Gen Comments
genComments collection =
  frequency
    [ (3, pure noComments)
    ,
      ( 1
      , Comments
          <$> genLines
          <*> oneof [pure Nothing, Just <$> genCommentText]
          <*> (if collection then genLines else pure [])
      )
    ]
  where
    genLines :: Gen [Line]
    genLines = do
      k <- choose (0, 2)
      vectorOf k (frequency [(3, CommentLine <$> elements [1, 1, 2, 3] <*> genCommentText), (1, pure EmptyLine)])

    genCommentText :: Gen T.Text
    genCommentText = elements ["a comment", "", "x", "# hash", "key: value", "- item", "'quoted'"]
