module RenderTests (renderTests) where

import Data.List qualified as L
import Data.Text qualified as T
import Test.QuickCheck
import Test.Tasty
import Test.Tasty.HUnit
import Test.Tasty.QuickCheck

import Yamlet.Syntax

renderTests :: TestTree
renderTests =
  testGroup
    "Render"
    [ testCase "workflow" test_workflow
    , testCase "styles" test_styles
    , testCase "fallbacks" test_fallbacks
    , testCase "force block" test_forceBlock
    , testCase "documents" test_documents
    , testGroup
        "comments"
        [ testCase "attachment" test_attachment
        , testCase "configuration" test_configuration
        , testCase "round trip" test_commentRoundTrip
        , testCase "moved comments" test_movedComments
        ]
    , testProperty "round trip" prop_roundTrip
    ]

-- | A generated file with a header, and empty lines between the jobs and
-- between the steps.
test_workflow :: Assertion
test_workflow = assertEqual "output" expected (renderSyntax defaultRenderOptions [doc])
  where
    doc :: Document
    doc =
      Document
        { version = Nothing
        , explicitStart = False
        , explicitEnd = False
        , docComments = noComments {before = [Comment "Generated by haskell-gha.\nDo not edit."]}
        , root =
            mappingNode
              [ (plainNode "name", plainNode "CI")
              ,
                ( withEmptyLine (plainNode "jobs")
                , mappingNode
                    [
                      ( withEmptyLine (plainNode "build")
                      , mappingNode
                          [ (plainNode "runs-on", plainNode "ubuntu-latest")
                          ,
                            ( plainNode "steps"
                            , sequenceNode
                                [ mappingNode [(plainNode "uses", plainNode "actions/checkout@v4")]
                                , withEmptyLine $
                                    mappingNode
                                      [ (plainNode "name", plainNode "Build")
                                      , (plainNode "run", scalarNode Literal "cabal build\ncabal test\n")
                                      ]
                                ]
                            )
                          ]
                      )
                    , (withEmptyLine (plainNode "lint"), mappingNode [(plainNode "ghc", scalarNode SingleQuoted "9.10")])
                    ]
                )
              ]
        }

    withEmptyLine :: Node -> Node
    withEmptyLine n = n {comments = n.comments {before = [EmptyLine]}}

    expected :: T.Text
    expected =
      T.unlines
        [ "# Generated by haskell-gha."
        , "# Do not edit."
        , "name: CI"
        , ""
        , "jobs:"
        , ""
        , "  build:"
        , "    runs-on: ubuntu-latest"
        , "    steps:"
        , "    - uses: actions/checkout@v4"
        , ""
        , "    - name: Build"
        , "      run: |"
        , "        cabal build"
        , "        cabal test"
        , ""
        , "  lint:"
        , "    ghc: '9.10'"
        ]

-- | Parsing and rendering gives back the input.
test_styles :: Assertion
test_styles = assertEqual "output" (Right input) (renderSyntax defaultRenderOptions <$> parseDocumentsText input)
  where
    input :: T.Text
    input =
      T.unlines
        [ "plain: text"
        , "single: 'it''s'"
        , "double: \"a\\tb\""
        , "literal: |"
        , "  line 1"
        , "   line 2"
        , "folded: >-"
        , "  first"
        , ""
        , "  second"
        , "list:"
        , "- a"
        , "- - b"
        , "  - c: d"
        , "flow: [a, 'b', {c: d}]"
        , "anchor: &x value"
        , "alias: *x"
        , "*x : key alias"
        , "tagged: !!str 12"
        , "local: !point {x: 1}"
        , "empty:"
        , "[complex, key]: value"
        ]

test_fallbacks :: Assertion
test_fallbacks = do
  let render :: Node -> T.Text
      render n = renderSyntax defaultRenderOptions [document n]
  assertEqual "plain with a colon" "'a: b'\n" (render (plainNode "a: b"))
  assertEqual "plain number stays plain" "12\n" (render (plainNode "12"))
  assertEqual "single-quoted line break" "\"a\\nb\"\n" (render (scalarNode SingleQuoted "a\nb"))
  assertEqual
    "keep indicator"
    "- \"a\\n\\n\"\n- b\n"
    (render (sequenceNode [scalarNode Literal "a\n\n", plainNode "b"]))
  assertEqual
    "block scalar in a flow collection"
    "[\"a\\n\"]\n"
    (render (contentNode (Sequence Flow [scalarNode Literal "a\n"])))
  assertEqual
    "empty item of a flow sequence"
    "[!!null, a]\n"
    (render (contentNode (Sequence Flow [plainNode "", plainNode "a"])))
  assertEqual "empty key" "?\n: a\n" (render (mappingNode [(plainNode "", plainNode "a")]))
  let anchored :: T.Text -> Node -> Node
      anchored a n = n {props = noProps {anchor = Just a}}
  assertEqual
    "invalid anchor names"
    "[&a_b x, *a_b, &a_b_2 y, *a_b_2, &anchor z, *anchor]\n"
    ( render . contentNode $
        Sequence
          Flow
          [ anchored "a b" (plainNode "x")
          , contentNode (Alias "a b")
          , anchored "a]b" (plainNode "y")
          , contentNode (Alias "a]b")
          , anchored "" (plainNode "z")
          , contentNode (Alias "")
          ]
    )
  assertEqual
    "taken anchor name"
    "- &a_b x\n- &a_b_2 y\n- *a_b_2\n"
    (render (sequenceNode [anchored "a_b" (plainNode "x"), anchored "a b" (plainNode "y"), contentNode (Alias "a b")]))

test_forceBlock :: Assertion
test_forceBlock =
  assertEqual
    "output"
    (Right expected)
    (renderSyntax defaultRenderOptions {forceBlock = True} <$> parseDocumentsText input)
  where
    input :: T.Text
    input = "list: [a, [b, c], {d: e}]\nkey: [[f]]\n"

    expected :: T.Text
    expected =
      T.unlines
        [ "list:"
        , "- a"
        , "- - b"
        , "  - c"
        , "- d: e"
        , "key:"
        , "- - f"
        ]

test_documents :: Assertion
test_documents = do
  let check :: String -> T.Text -> Assertion
      check preface input = assertEqual preface (Right input) (renderSyntax defaultRenderOptions <$> parseDocumentsText input)
  check "markers" $
    T.unlines
      [ "first"
      , "--- second"
      , "..."
      , "%YAML 1.2"
      , "---"
      , "a: b"
      , "---"
      ]
  check "comment after the end marker" "a: b\n...\n# c\nd: e\n"
  check "comment before the directives" "a\n...\n# b\n%YAML 1.2\n--- c\n"

-- | The comments of a document with the path of their nodes.
commentsOf :: Document -> [(String, String, T.Text)]
commentsOf doc = lines_ "document" doc.docComments ++ node "" doc.root
  where
    node :: String -> Node -> [(String, String, T.Text)]
    node path n = lines_ path n.comments {after = []} ++ inner ++ lines_ path noComments {after = n.comments.after}
      where
        inner :: [(String, String, T.Text)]
        inner = case n.content of
          Sequence _ xs -> concat (zipWith (\i x -> node (path ++ "/" ++ show i) x) [0 :: Int ..] xs)
          Mapping _ kvs -> concatMap (entry path) kvs
          _ -> []

    entry :: String -> (Node, Node) -> [(String, String, T.Text)]
    entry path (k, v) =
      let path' = path ++ "/" ++ keyText k
      in node (path' ++ ":key") k ++ node path' v

    keyText :: Node -> String
    keyText k = case k.content of
      Scalar _ t -> T.unpack t
      _ -> "?"

    lines_ :: String -> Comments -> [(String, String, T.Text)]
    lines_ path c =
      [(path, "before", t) | Comment t <- c.before]
        ++ [(path, "inline", t) | Just t <- [c.inline]]
        ++ [(path, "after", t) | Comment t <- c.after]

-- | Each rule of the documentation.
test_attachment :: Assertion
test_attachment = do
  let check :: String -> [(String, String, T.Text)] -> T.Text -> Assertion
      check preface expected input = case parseDocumentsText input of
        Right [doc] -> assertEqual preface expected (commentsOf doc)
        r -> assertFailure (preface ++ ": " ++ show r)
  check "above a key" [("/b:key", "before", "c")] "a: 1\n# c\nb: 2\n"
  check "above the first key" [("", "before", "c")] "# c\na: 1\n"
  check "at the end of a value" [("/a", "inline", "c")] "a: 1 # c\n"
  check "at the end of a key" [("/a:key", "inline", "c")] "a: # c\n  b: 1\n"
  check "on a block scalar header" [("/a", "inline", "c")] "a: | # c\n  text\n"
  check "above a sequence item" [("/a/1", "before", "c")] "a:\n- 1\n# c\n- 2\n"
  check "after a flow collection" [("/a", "inline", "c")] "a: [1, 2] # c\n"
  check "on an item line" [("/0", "inline", "c")] "- # c\n  a: 1\n"
  check "at the end of an indented list" [("/a", "after", "c")] "a:\n  - 1\n  # c\nb: 2\n"
  check "at the key column after a list" [("/b:key", "before", "c")] "a:\n- 1\n# c\nb: 2\n"
  check "at the end of a nested mapping" [("/a", "after", "c")] "a:\n  b: 1\n  # c\nd: 2\n"
  check "at the end of the root" [("", "after", "c")] "a: 1\n# c\n"
  check "at the end of the document" [("document", "after", "c")] "a\n# c\n"
  check "before the marker" [("document", "before", "c")] "# c\n---\na: 1\n"
  check "on the marker line" [("document", "inline", "c")] "--- # c\na: 1\n"
  check "after the end marker" [("document", "after", "c")] "a\n...\n# c\n"
  check "on the end marker line" [("document", "after", "c")] "a\n... # c\n"
  check "inside a flow sequence" [("/0", "inline", "c"), ("/1", "before", "d")] "[a, # c\n # d\n b]\n"
  check "empty lines" [] "a: 1\n\n\nb: 2\n"
  assertEqual
    "empty line"
    (Right [EmptyLine])
    ((\case [d] | Mapping _ [_, (k, _)] <- d.root.content -> k.comments.before; _ -> []) <$> parseDocumentsText "a: 1\n\n\nb: 2\n")

-- | The configuration of the haskell-gha test with comments.
test_configuration :: Assertion
test_configuration = case parseDocumentsText configuration of
  Right [doc] -> assertEqual "comments" expected (commentsOf doc)
  r -> assertFailure (show r)
  where
    expected :: [(String, String, T.Text)]
    expected =
      [ ("/matrix:key", "before", "The oldest and the newest supported Postgres.")
      , ("/services:key", "before", "The services of each build job.")
      , ("/services", "before", "The database for the tests.")
      , ("/services/postgres/env/POSTGRES_PASSWORD", "inline", "Only for CI.")
      , ("/permissions:key", "before", "The test reporter writes check runs.")
      , ("/permissions/checks:key", "before", "For the annotations of the test results.")
      , ("/hooks:key", "before", "The steps for Postgres.")
      , ("/hooks/before-build/1", "before", "Wait until the database accepts connections.")
      , ("/hooks/before-build", "after", "The database is ready for the build.")
      , ("/hooks/after-build", "after", "The tests come next.")
      ]

configuration :: T.Text
configuration =
  T.unlines
    [ "name: Postgres CI"
    , "branches: [master, 'release/**']"
    , "# The oldest and the newest supported Postgres."
    , "matrix:"
    , "  postgres: ['15', '18']"
    , "  exclude:"
    , "    - ghc: '9.10'"
    , "      postgres: '15'"
    , "apt: [libpq-dev, postgresql-client]"
    , "# The services of each build job."
    , "services:"
    , "  # The database for the tests."
    , "  postgres:"
    , "    image: postgres:${{ matrix.postgres }}"
    , "    env:"
    , "      POSTGRES_PASSWORD: postgres # Only for CI."
    , "    ports: ['5432:5432']"
    , "# The test reporter writes check runs."
    , "permissions:"
    , "  contents: read"
    , "  # For the annotations of the test results."
    , "  checks: write"
    , "# The steps for Postgres."
    , "hooks:"
    , "  before-build:"
    , "    - name: Show the Postgres version"
    , "      run: psql --version"
    , "    # Wait until the database accepts connections."
    , "    - name: Wait for Postgres"
    , "      run: |"
    , "        until pg_isready -h localhost; do"
    , "          sleep 1"
    , "        done"
    , "    # The database is ready for the build."
    , "  after-build:"
    , "    - name: Show the executables"
    , "      run: cabal list-bin all"
    , "    # The tests come next."
    , "ghc-options: -Werror -Wno-unused-imports"
    , "jobs: 2"
    ]

-- | Rendering keeps every comment, and a second round trip gives the same
-- text. The end comments of an indentless sequence belong to its last item
-- after the round trip.
test_commentRoundTrip :: Assertion
test_commentRoundTrip = case parseDocumentsText configuration of
  Right docs -> do
    let out = renderSyntax defaultRenderOptions docs
        texts :: Document -> [T.Text]
        texts d = [t | (_, _, t) <- commentsOf d]
    case parseDocumentsText out of
      Right docs' -> do
        assertEqual ("comments\n" ++ T.unpack out) (map texts docs) (map texts docs')
        assertEqual "text" out (renderSyntax defaultRenderOptions docs')
      Left err -> assertFailure (T.unpack out ++ "\n" ++ show err)
  Left err -> assertFailure (show err)

-- | A comment without a place at its node moves to one that has it.
test_movedComments :: Assertion
test_movedComments = do
  let render :: Node -> T.Text
      render n = renderSyntax defaultRenderOptions [document n]
      withInline :: T.Text -> Node -> Node
      withInline t n = n {comments = n.comments {inline = Just t}}
      withBefore :: T.Text -> Node -> Node
      withBefore t n = n {comments = n.comments {before = [Comment t]}}
  assertEqual
    "lines above a value on the line of the key"
    "# v\na: 1\n"
    (render (mappingNode [(plainNode "a", withBefore "v" (plainNode "1"))]))
  assertEqual
    "two comments on one line"
    "# k\na: 1 # v\n"
    (render (mappingNode [(withInline "k" (plainNode "a"), withInline "v" (plainNode "1"))]))
  assertEqual
    "comment in a flow sequence"
    "a:\n- 1 # c\n- 2\n"
    (render (mappingNode [(plainNode "a", contentNode (Sequence Flow [withInline "c" (plainNode "1"), plainNode "2"]))]))
  assertEqual
    "comment on a block root"
    "--- # c\na: 1\n"
    (render (withInline "c" (mappingNode [(plainNode "a", plainNode "1")])))
  let withAfter :: T.Text -> Node -> Node
      withAfter t n = n {comments = n.comments {after = [Comment t]}}
      list :: Node -> Node
      list item =
        mappingNode
          [ (plainNode "a", withAfter "c" (sequenceNode [item]))
          , (plainNode "b", plainNode "2")
          ]
  assertEqual
    "end of an indentless list"
    "a:\n- x: 1\n  # c\nb: 2\n"
    (render (list (mappingNode [(plainNode "x", plainNode "1")])))
  assertEqual
    "end of a list with a block scalar"
    "a:\n  - |\n    x\n  # c\nb: 2\n"
    (render (list (scalarNode Literal "x\n")))

-- | Rendering a tree and parsing the result gives the same tree, except for
-- the styles, the offsets and the places of the comments. Every comment
-- stays, and rendering the result again gives the same text.
prop_roundTrip :: Tree -> Property
prop_roundTrip (Tree doc) =
  let out = renderSyntax defaultRenderOptions [doc]
  in counterexample (T.unpack out) $ case parseDocumentsText out of
       Right [doc'] ->
         conjoin
           [ counterexample "tree" $ strip doc'.root === strip (flowItems False doc.root)
           , counterexample "comments" $ L.sort (allComments doc') === L.sort (allComments doc)
           , let out' = renderSyntax defaultRenderOptions [doc']
             in counterexample ("text: " ++ firstDifference out out') (out' == out)
           ]
       r -> counterexample (show r) False
  where
    strip :: Node -> Node
    strip n =
      ( contentNode $ case n.content of
          Scalar _ t -> Scalar Plain t
          Sequence _ xs -> Sequence Block (map strip xs)
          Mapping _ kvs -> Mapping Block [(strip k, strip v) | (k, v) <- kvs]
          Alias a -> Alias a
      )
        { props = n.props
        }

    allComments :: Document -> [T.Text]
    allComments d = [t | (_, _, t) <- commentsOf d]

    -- The renderer gives an empty item of a flow sequence a tag.
    flowItems :: Bool -> Node -> Node
    flowItems inFlow n = case n.content of
      Sequence s xs ->
        let inFlow' = inFlow || (s == Flow && not (hasComments n))
        in n {content = Sequence s (map (item inFlow' . flowItems inFlow') xs)}
      Mapping s kvs ->
        let inFlow' = inFlow || (s == Flow && not (hasComments n))
        in n {content = Mapping s [(flowItems inFlow' k, flowItems inFlow' v) | (k, v) <- kvs]}
      _ -> n

    item :: Bool -> Node -> Node
    item inFlow n = case (n.props, n.content) of
      (Props Nothing NoTag, Scalar Plain "")
        | inFlow ->
            n {props = Props Nothing (Tag "tag:yaml.org,2002:null")}
      _ -> n

    -- A flow collection with comments inside becomes a block collection.
    hasComments :: Node -> Bool
    hasComments n =
      not (null [() | Comment _ <- n.comments.after]) || case n.content of
        Sequence _ xs -> any inner xs
        Mapping _ kvs -> any (\(k, v) -> inner k || inner v) kvs
        _ -> False
      where
        inner :: Node -> Bool
        inner x =
          not (null [() | Comment _ <- x.comments.before])
            || x.comments.inline /= Nothing
            || hasComments x

newtype Tree = Tree Document
  deriving stock (Show)

instance Arbitrary Tree where
  arbitrary = do
    root <- sized genNode
    c <- genComments False
    pure . Tree $ (document root) {docComments = c}

genNode :: Int -> Gen Node
genNode size = do
  n <-
    if size <= 1
      then genScalar
      else
        frequency
          [ (3, genScalar)
          , (1, contentNode . Alias <$> genAnchor)
          , (1, contentNode <$> (Sequence <$> genStyle <*> genList))
          , (1, contentNode <$> (Mapping <$> genStyle <*> genEntries))
          ]
  p <- case n.content of
    Alias _ -> pure noProps
    _ -> genProps
  c <- genComments (isCollection n)
  pure n {props = p, comments = c}
  where
    genList :: Gen [Node]
    genList = do
      k <- choose (0, 4)
      vectorOf k (genNode (size `div` 3))

    genEntries :: Gen [(Node, Node)]
    genEntries = do
      k <- choose (0, 4)
      vectorOf k ((,) <$> genNode (size `div` 4) <*> genNode (size `div` 3))

    genStyle :: Gen CollectionStyle
    genStyle = elements [Block, Flow]

    isCollection :: Node -> Bool
    isCollection n = case n.content of
      Sequence _ (_ : _) -> True
      Mapping _ (_ : _) -> True
      _ -> False

-- | Comments for a node. Only a non-empty collection has lines after it.
genComments :: Bool -> Gen Comments
genComments collection =
  frequency
    [ (3, pure noComments)
    ,
      ( 1
      , Comments
          <$> genLines
          <*> oneof [pure Nothing, Just <$> genCommentText]
          <*> (if collection then genLines else pure [])
      )
    ]
  where
    genLines :: Gen [Line]
    genLines = do
      k <- choose (0, 2)
      vectorOf k (frequency [(3, Comment <$> genCommentText), (1, pure EmptyLine)])

genCommentText :: Gen T.Text
genCommentText = elements ["a comment", "", "x", "# hash", "key: value", "- item", "'quoted'"]

genScalar :: Gen Node
genScalar = scalarNode <$> elements [minBound .. maxBound] <*> genText

genProps :: Gen Props
genProps =
  Props
    <$> oneof [pure Nothing, Just <$> genAnchor]
    <*> elements
      [ NoTag
      , NoTag
      , NonSpecificTag
      , Tag "tag:yaml.org,2002:str"
      , Tag "!local"
      , Tag "tag:example.com,2000:x"
      ]

genAnchor :: Gen T.Text
genAnchor = elements ["a", "b", "anchor"]

genText :: Gen T.Text
genText =
  oneof
    [ elements tricky
    , T.pack <$> listOf genChar
    , T.intercalate "\n" <$> listOf (T.pack <$> listOf genChar)
    ]
  where
    tricky :: [T.Text]
    tricky =
      [ ""
      , " "
      , "-"
      , "- a"
      , "? a"
      , ": a"
      , "a: b"
      , "a:b"
      , "#"
      , "a #b"
      , "true"
      , "12"
      , "---"
      , "..."
      , "foo\n"
      , "\nfoo"
      , "  lead"
      , "trail  "
      , "a\n\nb\n\n"
      , "\n"
      , "\n\n"
      , " \n"
      , "a\n "
      , "|"
      , ">"
      , "[a]"
      , "{a: b}"
      , "a, b"
      , "key:"
      , "\r\n"
      , "a\n  b\nc"
      , "  a\nb"
      , "a\n\n  b\n\nc\n"
      ]

    genChar :: Gen Char
    genChar =
      frequency
        [ (10, elements "abc xyz-:#,[]{}'\"!&*?|>%@`\\")
        , (2, elements "\t\r\x85\xA0\x2028\xFEFF\x01")
        , (1, arbitrary)
        ]

-- | The first line where two texts differ, with the line before it.
firstDifference :: T.Text -> T.Text -> String
firstDifference a b = go (1 :: Int) "" (T.lines a) (T.lines b)
  where
    go :: Int -> T.Text -> [T.Text] -> [T.Text] -> String
    go n prev xs ys = case (xs, ys) of
      (x : xs', y : ys') | x == y -> go (n + 1) x xs' ys'
      _ ->
        "line "
          ++ show n
          ++ " after "
          ++ show prev
          ++ ": "
          ++ show (take 1 xs)
          ++ " /= "
          ++ show (take 1 ys)
